env: 'local'

origin: 'http://localhost:5173'

server:
  host: 'localhost'
  port: 8888
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 30s
  idleTimeout: 60s

database:
  username: 'postgres'
  password: 'root'
  host: 'localhost'
  port: '5432'
  dbName: 'visualizer-db-stage'
  SSLMode: 'disable'

jwt:
  signingKey: 'jwt-secret'
  accessTokenTTL: 10
  refreshTokenTTL: 100

cookie:
  accessToken:
    name: 'access_token'
    maxAge: 86400s
    secure: true
    httpOnly: true
