env: 'prod'

origin: 'http://stage.visualizer.imby.energy'

server:
  host: 'localhost'
  port: 8888
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

database:
  username: 'postgres'
  password: 'root'
  host: 'localhost'
  port: '5432'
  dbName: 'visualizer-dev-db'
  SSLMode: 'disable'

jwt:
  secret: 'jwt-secret'
