// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "responses": {}
            }
        },
        "/dashboards": {
            "get": {
                "tags": [
                    "Dashboards"
                ],
                "summary": "Get all dashboards",
                "responses": {}
            },
            "post": {
                "tags": [
                    "Dashboards"
                ],
                "summary": "Create dashboard",
                "responses": {}
            },
            "patch": {
                "tags": [
                    "Dashboards"
                ],
                "summary": "Update dashboard",
                "responses": {}
            }
        },
        "/dashboards/share/{id}": {
            "get": {
                "tags": [
                    "Dashboards"
                ],
                "summary": "Get dashboard by share id",
                "responses": {}
            }
        },
        "/dashboards/t/{id}": {
            "get": {
                "tags": [
                    "Dashboards"
                ],
                "summary": "Get dashboards by template id",
                "responses": {}
            }
        },
        "/dashboards/{id}": {
            "get": {
                "tags": [
                    "Dashboards"
                ],
                "summary": "Get dashboard by id",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Dashboards"
                ],
                "summary": "Delete dashboard",
                "responses": {}
            }
        },
        "/dashboards/{id}/metric": {
            "patch": {
                "tags": [
                    "Dashboards"
                ],
                "summary": "Metric dashboard",
                "responses": {}
            }
        },
        "/diagrams": {
            "get": {
                "tags": [
                    "Diagrams"
                ],
                "summary": "Get all diagrams",
                "responses": {}
            },
            "post": {
                "tags": [
                    "Diagrams"
                ],
                "summary": "Create diagram",
                "responses": {}
            }
        },
        "/diagrams/{id}": {
            "get": {
                "tags": [
                    "Diagrams"
                ],
                "summary": "Get diagram by id",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Diagrams"
                ],
                "summary": "Delete diagram",
                "responses": {}
            },
            "patch": {
                "tags": [
                    "Diagrams"
                ],
                "summary": "Update diagram",
                "responses": {}
            }
        },
        "/templates": {
            "get": {
                "description": "Returns all templates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Returns all templates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/templates.Template"
                            }
                        }
                    }
                }
            }
        },
        "/templates/{id}": {
            "get": {
                "description": "Returns template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Returns template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/templates.Template"
                        }
                    }
                }
            },
            "post": {
                "description": "Create template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Create template",
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "patch": {
                "description": "Update template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Update template",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Create user",
                "responses": {}
            }
        },
        "/users/me": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Get current user",
                "responses": {}
            }
        },
        "/users/{id}": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Get user by id",
                "responses": {}
            },
            "patch": {
                "tags": [
                    "Users"
                ],
                "summary": "Update user",
                "responses": {}
            }
        }
    },
    "definitions": {
        "templates.Template": {
            "type": "object",
            "required": [
                "creatorId"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "creatorId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "uses": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your bearer token in the format **Bearer \u0026lt;token\u0026gt;**",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Visualizer REST API",
	Description:      "A REST API in Go using Gin framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
