name: Analytics

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Count lines
        run: cloc .
